### ISSUE TITLE
it doesn't connect to gcp cloud sql admin api

### ISSUE THREAD

**Issue by noonkott** [freelec/gcp-compute-engine#1]
I followed the guide book chapter '2.4.3 Data Management with Cloud SQL' and 
after enabling the Cloud SQL Admin API,
I still failed to connect Cloud SQL Admin API and get following error message log:
------------------------------
googleapi: Error 403: Cloud SQL Admin API has not been used in project 731100712924 
before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=731100712924 then retry. 
...
webserver app.py[3476]: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 2] No such file or directory)"
-----------------------------
Below part seems due to the above error.

Do I need to use IAM or API keys to do it? Additional Auth is not described in the book.
Please guide how I can connect SQL Admin API and clear the errors.

Thank you and pls understand if this post is not appropriate place.

**Comment by pacon21** [comment]
Hi~

* Setting the Cloud API access scopes for an instance
  Go to the VM instances page in the Compute Engine
  Click the VM instance name for which you want to change the service account.
  If the instance is not stopped, click the Stop button. Wait for the instance to be stopped.
  click the Edit button.
  Scroll down to the Service Account section.
  From the dropdown menu, select the desired service account.
  To change scopes, in the Access scopes section, set the appropriate scopes for your needs.
      
I hope this helps.

**Comment by noonkott** [comment]
Thank you for kind comment.
I finally found the API permission setting was wrong (wasn't allowed) and solved the above error.
Appreciated!

**Comment by noonkott** [comment]
hello

In chap.3, in order to start automatically the
web application (dengonban.service and cloudsqlproxy.service)
with multiple vm with a load balancing ,
i add start script in vm instance template but it doesnot work.

#!/bin/bash
sudo systemctl start cloudsqlproxy.service
sudo systemctl start dengonban.service
...

could you guide me how to do it in this case?

thank you in advance.

noonkott

2019년 5월 11일 (토) 오후 5:58, In-Su Kim <notifications@github.com>님이 작성:
